-- AlterTable
ALTER TABLE "Cliente" ALTER COLUMN "relacionamento" SET DEFAULT 50,
ALTER COLUMN "relacionamento" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "confianca" SET DEFAULT 50,
ALTER COLUMN "confianca" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Empresa" ALTER COLUMN "reputacao" SET DEFAULT 40,
ALTER COLUMN "reputacao" SET DATA TYPE DOUBLE PRECISION;
